# Generated by Django 3.2.3 on 2021-05-19 07:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20210518_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='education.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Текст статьи'),
        ),
    ]
