# Generated by Django 3.2.3 on 2021-05-21 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0008_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Mentor',
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
