# Generated by Django 3.2.3 on 2021-05-21 08:35

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Название')),
                ('text', tinymce.models.HTMLField(blank=True, default='', verbose_name='Текст занятия')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='education.course', verbose_name='Курс')),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='education.mentor', verbose_name='Преподаватель')),
                ('tags', models.ManyToManyField(related_name='lessons', to='education.Tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.lesson', verbose_name='Статья'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
