# Generated by Django 3.2.3 on 2021-05-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20210521_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
