# Generated by Django 3.2.3 on 2021-05-23 09:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_alter_schedule_lesson_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Описание урока'),
        ),
    ]
